"""
Generate Feature 8 Jupyter Notebook with 17 cells exactly matching the user specification.
"""

import os
import json

def create_notebook():
    cells = [
        # Cell 1 - Markdown
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Feature 8 — India Supply-Route Disruption Intelligence 🇮🇳🚢\n",
                "### GeoPulse AI — Global Conflict Impact Intelligence Platform\n",
                "\n",
                "#### Objective\n",
                "Predict whether a geopolitical disruption to an important shipping/trade route creates **Low**, **Moderate**, **High** or **Critical** supply-route risk for India.\n",
                "\n",
                "#### Real-life question\n",
                "*“Agar Red Sea, Suez Canal, Strait of Hormuz ya kisi important trade route mein disruption ho, toh India ke imports/exports aur supply movement ke liye risk kitna hai?”*\n",
                "\n",
                "The feature converts route-disruption conditions into a trained classification prediction for India.\n",
                "\n",
                "#### Strict syllabus mapping\n",
                "- **Module 3:** Logistic Regression, k-NN, Decision Tree, Random Forest, SVM\n",
                "- **Module 5:** Train/Test Split, Cross Validation, Confusion Matrix, Accuracy, Precision, Recall, F1, ROC-AUC, Overfitting/Underfitting, Hyperparameter Tuning\n",
                "- **Module 6:** Data preprocessing, model development, evaluation, visualization and result interpretation\n",
                "\n",
                "#### Important restriction\n",
                "Use **only** the five syllabus classifiers:\n",
                "1. Logistic Regression\n",
                "2. k-NN\n",
                "3. Decision Tree\n",
                "4. Random Forest\n",
                "5. SVM\n",
                "\n",
                "*Do NOT use Naive Bayes, XGBoost, LSTM, ARIMA, Transformers, BERT, neural networks or other out-of-syllabus classifiers.*\n",
                "\n",
                "#### End-to-end workflow\n",
                "Real labelled route/event data → preprocessing → five syllabus classifiers → cross-validation → model comparison → hyperparameter tuning → evaluation → best model → live route-disruption prediction → save model."
            ]
        },
        # Cell 2 - Markdown
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## Dataset\n",
                "Place a real labelled CSV at:\n",
                "`data/feature8_india_supply_route_risk.csv`\n",
                "\n",
                "### Required columns\n",
                "- `route`: relevant shipping/trade route.\n",
                "- `country_or_region`: associated country/region.\n",
                "- `event_date`: occurrence date of the event.\n",
                "- `route_disruption`: measured/documented disruption level (0-100).\n",
                "- `shipping_delay`: observed or documented delay indicator in days.\n",
                "- `freight_cost_change`: percentage change in freight/shipping cost.\n",
                "- `trade_volume_exposure`: India-relevant trade exposure through the route (0-100).\n",
                "- `india_import_exposure`: India's import exposure through the route (0-100).\n",
                "- `india_export_exposure`: India's export exposure through the route (0-100).\n",
                "- `energy_route_exposure`: India's energy exposure through the route (0-100).\n",
                "- `commodity_exposure`: commodity exposure through the route (0-100).\n",
                "- `conflict_intensity`: documented/quantified conflict intensity (0-100).\n",
                "- `supply_route_risk`: classification target (`Low`, `Moderate`, `High`, `Critical`)."
            ]
        },
        # Cell 3 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 2 — Imports, configuration and dataset loading\n",
                "\n",
                "import os\n",
                "import numpy as np\n",
                "import pandas as pd\n",
                "import matplotlib.pyplot as plt\n",
                "\n",
                "from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV\n",
                "from sklearn.pipeline import Pipeline\n",
                "from sklearn.impute import SimpleImputer\n",
                "from sklearn.preprocessing import StandardScaler, label_binarize\n",
                "from sklearn.linear_model import LogisticRegression\n",
                "from sklearn.neighbors import KNeighborsClassifier\n",
                "from sklearn.tree import DecisionTreeClassifier\n",
                "from sklearn.ensemble import RandomForestClassifier\n",
                "from sklearn.svm import SVC\n",
                "from sklearn.metrics import (\n",
                "    accuracy_score, precision_score, recall_score, f1_score,\n",
                "    confusion_matrix, ConfusionMatrixDisplay,\n",
                "    classification_report, roc_auc_score, roc_curve, auc\n",
                ")\n",
                "\n",
                "RANDOM_STATE = 42\n",
                "DATA_PATH = \"data/feature8_india_supply_route_risk.csv\"\n",
                "\n",
                "if not os.path.exists(DATA_PATH):\n",
                "    raise FileNotFoundError(\n",
                "        f\"Dataset not found: {DATA_PATH}. Add the real labelled CSV first.\"\n",
                "    )\n",
                "\n",
                "df = pd.read_csv(DATA_PATH)\n",
                "\n",
                "print(\"Dataset shape:\", df.shape)\n",
                "df.head()"
            ]
        },
        # Cell 4 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 3 — Validate columns and preprocess the dataset\n",
                "\n",
                "required = {\n",
                "    \"route\",\n",
                "    \"country_or_region\",\n",
                "    \"event_date\",\n",
                "    \"route_disruption\",\n",
                "    \"shipping_delay\",\n",
                "    \"freight_cost_change\",\n",
                "    \"trade_volume_exposure\",\n",
                "    \"india_import_exposure\",\n",
                "    \"india_export_exposure\",\n",
                "    \"energy_route_exposure\",\n",
                "    \"commodity_exposure\",\n",
                "    \"conflict_intensity\",\n",
                "    \"supply_route_risk\"\n",
                "}\n",
                "\n",
                "missing = required - set(df.columns)\n",
                "\n",
                "if missing:\n",
                "    raise ValueError(f\"Missing required columns: {sorted(missing)}\")\n",
                "\n",
                "numeric = [\n",
                "    \"route_disruption\",\n",
                "    \"shipping_delay\",\n",
                "    \"freight_cost_change\",\n",
                "    \"trade_volume_exposure\",\n",
                "    \"india_import_exposure\",\n",
                "    \"india_export_exposure\",\n",
                "    \"energy_route_exposure\",\n",
                "    \"commodity_exposure\",\n",
                "    \"conflict_intensity\"\n",
                "]\n",
                "\n",
                "for col in numeric:\n",
                "    df[col] = pd.to_numeric(df[col], errors=\"coerce\")\n",
                "\n",
                "df[\"event_date\"] = pd.to_datetime(df[\"event_date\"], errors=\"coerce\")\n",
                "df[\"route\"] = df[\"route\"].astype(str).str.strip()\n",
                "df[\"country_or_region\"] = df[\"country_or_region\"].astype(str).str.strip()\n",
                "df[\"supply_route_risk\"] = df[\"supply_route_risk\"].astype(str).str.strip()\n",
                "\n",
                "before = len(df)\n",
                "\n",
                "df = df.drop_duplicates()\n",
                "df = df.dropna(\n",
                "    subset=numeric + [\"route\", \"country_or_region\", \"event_date\", \"supply_route_risk\"]\n",
                ")\n",
                "\n",
                "print(\"Rows before cleaning:\", before)\n",
                "print(\"Rows after cleaning :\", len(df))\n",
                "\n",
                "print(\"\\nRisk distribution:\")\n",
                "df[\"supply_route_risk\"].value_counts()"
            ]
        },
        # Cell 5 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 4 — Visualize supply-route risk distribution\n",
                "\n",
                "plt.figure(figsize=(8, 5))\n",
                "\n",
                "df[\"supply_route_risk\"].value_counts().plot(\n",
                "    kind=\"bar\",\n",
                "    color=[\"#3b82f6\", \"#eab308\", \"#f97316\", \"#ef4444\"]\n",
                ")\n",
                "\n",
                "plt.title(\"India Supply-Route Risk Distribution\")\n",
                "plt.xlabel(\"Supply Route Risk\")\n",
                "plt.ylabel(\"Number of Records\")\n",
                "plt.xticks(rotation=0)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        },
        # Cell 6 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 5 — Feature selection and stratified train/test split\n",
                "\n",
                "features = [\n",
                "    \"route_disruption\",\n",
                "    \"shipping_delay\",\n",
                "    \"freight_cost_change\",\n",
                "    \"trade_volume_exposure\",\n",
                "    \"india_import_exposure\",\n",
                "    \"india_export_exposure\",\n",
                "    \"energy_route_exposure\",\n",
                "    \"commodity_exposure\",\n",
                "    \"conflict_intensity\"\n",
                "]\n",
                "\n",
                "X = df[features]\n",
                "y = df[\"supply_route_risk\"]\n",
                "\n",
                "X_train, X_test, y_train, y_test = train_test_split(\n",
                "    X,\n",
                "    y,\n",
                "    test_size=0.20,\n",
                "    random_state=RANDOM_STATE,\n",
                "    stratify=y\n",
                ")\n",
                "\n",
                "print(\"Training records:\", len(X_train))\n",
                "print(\"Testing records :\", len(X_test))\n",
                "print(\"\\nFeatures:\")\n",
                "print(features)"
            ]
        },
        # Cell 7 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 6 — Train the five syllabus-aligned classifiers\n",
                "\n",
                "models = {\n",
                "    \"Logistic Regression\": Pipeline([\n",
                "        (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
                "        (\"scale\", StandardScaler()),\n",
                "        (\"model\", LogisticRegression(max_iter=2000, random_state=RANDOM_STATE))\n",
                "    ]),\n",
                "\n",
                "    \"k-NN\": Pipeline([\n",
                "        (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
                "        (\"scale\", StandardScaler()),\n",
                "        (\"model\", KNeighborsClassifier(n_neighbors=5))\n",
                "    ]),\n",
                "\n",
                "    \"Decision Tree\": Pipeline([\n",
                "        (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
                "        (\"model\", DecisionTreeClassifier(max_depth=10, random_state=RANDOM_STATE))\n",
                "    ]),\n",
                "\n",
                "    \"Random Forest\": Pipeline([\n",
                "        (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
                "        (\"model\", RandomForestClassifier(\n",
                "            n_estimators=150,\n",
                "            random_state=RANDOM_STATE,\n",
                "            n_jobs=-1\n",
                "        ))\n",
                "    ]),\n",
                "\n",
                "    \"SVM\": Pipeline([\n",
                "        (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
                "        (\"scale\", StandardScaler()),\n",
                "        (\"model\", SVC(\n",
                "            kernel=\"linear\",\n",
                "            probability=True,\n",
                "            random_state=RANDOM_STATE\n",
                "        ))\n",
                "    ])\n",
                "}\n",
                "\n",
                "results = []\n",
                "trained = {}\n",
                "\n",
                "for name, model in models.items():\n",
                "    model.fit(X_train, y_train)\n",
                "    pred = model.predict(X_test)\n",
                "\n",
                "    trained[name] = model\n",
                "\n",
                "    results.append({\n",
                "        \"Model\": name,\n",
                "        \"Accuracy\": accuracy_score(y_test, pred),\n",
                "        \"Precision\": precision_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        ),\n",
                "        \"Recall\": recall_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        ),\n",
                "        \"F1\": f1_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        )\n",
                "    })\n",
                "\n",
                "results = (\n",
                "    pd.DataFrame(results)\n",
                "    .sort_values(\"F1\", ascending=False)\n",
                "    .reset_index(drop=True)\n",
                ")\n",
                "\n",
                "results"
            ]
        },
        # Cell 8 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 7 — Five-fold stratified cross-validation\n",
                "\n",
                "cv = StratifiedKFold(\n",
                "    n_splits=5,\n",
                "    shuffle=True,\n",
                "    random_state=RANDOM_STATE\n",
                ")\n",
                "\n",
                "cv_rows = []\n",
                "\n",
                "for name, model in models.items():\n",
                "\n",
                "    scores = cross_val_score(\n",
                "        model,\n",
                "        X_train,\n",
                "        y_train,\n",
                "        cv=cv,\n",
                "        scoring=\"f1_weighted\",\n",
                "        n_jobs=-1\n",
                "    )\n",
                "\n",
                "    cv_rows.append({\n",
                "        \"Model\": name,\n",
                "        \"Mean CV F1\": scores.mean(),\n",
                "        \"CV Std\": scores.std()\n",
                "    })\n",
                "\n",
                "cv_results = (\n",
                "    pd.DataFrame(cv_rows)\n",
                "    .sort_values(\"Mean CV F1\", ascending=False)\n",
                "    .reset_index(drop=True)\n",
                ")\n",
                "\n",
                "cv_results"
            ]
        },
        # Cell 9 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 8 — Confusion matrix for the current best test-set model\n",
                "\n",
                "best_name = results.iloc[0][\"Model\"]\n",
                "best_model = trained[best_name]\n",
                "\n",
                "pred = best_model.predict(X_test)\n",
                "\n",
                "labels = sorted(y.unique())\n",
                "\n",
                "cm = confusion_matrix(\n",
                "    y_test,\n",
                "    pred,\n",
                "    labels=labels\n",
                ")\n",
                "\n",
                "fig, ax = plt.subplots(figsize=(7, 6))\n",
                "\n",
                "ConfusionMatrixDisplay(\n",
                "    confusion_matrix=cm,\n",
                "    display_labels=labels\n",
                ").plot(\n",
                "    ax=ax,\n",
                "    xticks_rotation=30,\n",
                "    cmap=\"Blues\"\n",
                ")\n",
                "\n",
                "ax.set_title(f\"Confusion Matrix — {best_name}\")\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "print(classification_report(\n",
                "    y_test,\n",
                "    pred,\n",
                "    zero_division=0\n",
                "))"
            ]
        },
        # Cell 10 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 9 — ROC-AUC and ROC curves\n",
                "\n",
                "if hasattr(best_model, \"predict_proba\"):\n",
                "\n",
                "    proba = best_model.predict_proba(X_test)\n",
                "    y_bin = label_binarize(\n",
                "        y_test,\n",
                "        classes=labels\n",
                "    )\n",
                "\n",
                "    if len(labels) > 2:\n",
                "        roc_auc = roc_auc_score(\n",
                "            y_bin,\n",
                "            proba,\n",
                "            multi_class=\"ovr\",\n",
                "            average=\"weighted\"\n",
                "        )\n",
                "    else:\n",
                "        roc_auc = roc_auc_score(\n",
                "            y_bin,\n",
                "            proba[:, 1]\n",
                "        )\n",
                "\n",
                "    print(\"Weighted ROC-AUC:\", roc_auc)\n",
                "\n",
                "    plt.figure(figsize=(8, 6))\n",
                "\n",
                "    for i, label in enumerate(labels):\n",
                "\n",
                "        if y_bin[:, i].sum() in (0, len(y_bin)):\n",
                "            continue\n",
                "\n",
                "        fpr, tpr, _ = roc_curve(\n",
                "            y_bin[:, i],\n",
                "            proba[:, i]\n",
                "        )\n",
                "\n",
                "        plt.plot(\n",
                "            fpr,\n",
                "            tpr,\n",
                "            label=f\"{label} (AUC={auc(fpr, tpr):.3f})\"\n",
                "        )\n",
                "\n",
                "    plt.plot(\n",
                "        [0, 1],\n",
                "        [0, 1],\n",
                "        linestyle=\"--\",\n",
                "        color=\"gray\"\n",
                "    )\n",
                "\n",
                "    plt.xlabel(\"False Positive Rate\")\n",
                "    plt.ylabel(\"True Positive Rate\")\n",
                "    plt.title(f\"ROC Curve — {best_name}\")\n",
                "    plt.legend()\n",
                "\n",
                "    plt.tight_layout()\n",
                "    plt.show()\n",
                "\n",
                "else:\n",
                "    print(\"ROC-AUC unavailable for this model configuration.\")"
            ]
        },
        # Cell 11 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 10 — Hyperparameter tuning\n",
                "\n",
                "grids = {\n",
                "    \"Logistic Regression\": {\n",
                "        \"model__C\": [0.1, 1, 10]\n",
                "    },\n",
                "\n",
                "    \"k-NN\": {\n",
                "        \"model__n_neighbors\": [3, 5, 7, 9]\n",
                "    },\n",
                "\n",
                "    \"Decision Tree\": {\n",
                "        \"model__max_depth\": [5, 10, 15, None]\n",
                "    },\n",
                "\n",
                "    \"Random Forest\": {\n",
                "        \"model__n_estimators\": [100, 150],\n",
                "        \"model__max_depth\": [8, 12, None]\n",
                "    },\n",
                "\n",
                "    \"SVM\": {\n",
                "        \"model__C\": [0.1, 1, 10]\n",
                "    }\n",
                "}\n",
                "\n",
                "tuned = {}\n",
                "\n",
                "for name, grid in grids.items():\n",
                "\n",
                "    search = GridSearchCV(\n",
                "        models[name],\n",
                "        grid,\n",
                "        cv=cv,\n",
                "        scoring=\"f1_weighted\",\n",
                "        n_jobs=-1\n",
                "    )\n",
                "\n",
                "    search.fit(X_train, y_train)\n",
                "\n",
                "    tuned[name] = search.best_estimator_\n",
                "\n",
                "    print(\"\\n\", name)\n",
                "    print(\"Best CV F1:\", search.best_score_)\n",
                "    print(\"Best parameters:\", search.best_params_)"
            ]
        },
        # Cell 12 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 11 — Compare tuned models\n",
                "\n",
                "final_rows = []\n",
                "\n",
                "for name, model in tuned.items():\n",
                "\n",
                "    pred = model.predict(X_test)\n",
                "\n",
                "    final_rows.append({\n",
                "        \"Model\": name,\n",
                "        \"Accuracy\": accuracy_score(y_test, pred),\n",
                "        \"Precision\": precision_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        ),\n",
                "        \"Recall\": recall_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        ),\n",
                "        \"F1\": f1_score(\n",
                "            y_test, pred, average=\"weighted\", zero_division=0\n",
                "        )\n",
                "    })\n",
                "\n",
                "final_results = (\n",
                "    pd.DataFrame(final_rows)\n",
                "    .sort_values(\"F1\", ascending=False)\n",
                "    .reset_index(drop=True)\n",
                ")\n",
                "\n",
                "print(\"Final Model Comparison:\")\n",
                "print(final_results)\n",
                "\n",
                "BEST_MODEL_NAME = final_results.iloc[0][\"Model\"]\n",
                "BEST_MODEL = tuned[BEST_MODEL_NAME]\n",
                "\n",
                "print(\"\\nBest model:\", BEST_MODEL_NAME)"
            ]
        },
        # Cell 13 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 12 — Overfitting / Underfitting analysis\n",
                "\n",
                "fit_rows = []\n",
                "\n",
                "for name, model in tuned.items():\n",
                "\n",
                "    train_pred = model.predict(X_train)\n",
                "    test_pred = model.predict(X_test)\n",
                "\n",
                "    train_f1 = f1_score(\n",
                "        y_train,\n",
                "        train_pred,\n",
                "        average=\"weighted\",\n",
                "        zero_division=0\n",
                "    )\n",
                "\n",
                "    test_f1 = f1_score(\n",
                "        y_test,\n",
                "        test_pred,\n",
                "        average=\"weighted\",\n",
                "        zero_division=0\n",
                "    )\n",
                "\n",
                "    fit_rows.append({\n",
                "        \"Model\": name,\n",
                "        \"Train F1\": train_f1,\n",
                "        \"Test F1\": test_f1,\n",
                "        \"Train-Test Gap\": train_f1 - test_f1\n",
                "    })\n",
                "\n",
                "fit_results = (\n",
                "    pd.DataFrame(fit_rows)\n",
                "    .sort_values(\"Test F1\", ascending=False)\n",
                "    .reset_index(drop=True)\n",
                ")\n",
                "\n",
                "fit_results"
            ]
        },
        # Cell 14 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 13 — Route-wise risk analysis\n",
                "\n",
                "route_risk = (\n",
                "    df.groupby([\"route\", \"supply_route_risk\"])\n",
                "      .size()\n",
                "      .reset_index(name=\"records\")\n",
                "      .sort_values(\"records\", ascending=False)\n",
                ")\n",
                "\n",
                "print(\"Route Risk Distribution (Top records):\")\n",
                "print(route_risk.head(20))\n",
                "\n",
                "# Average disruption indicators by route\n",
                "route_summary = (\n",
                "    df.groupby(\"route\")[\n",
                "        [\n",
                "            \"route_disruption\",\n",
                "            \"shipping_delay\",\n",
                "            \"freight_cost_change\",\n",
                "            \"india_import_exposure\",\n",
                "            \"energy_route_exposure\"\n",
                "        ]\n",
                "    ]\n",
                "    .mean()\n",
                "    .sort_values(\"india_import_exposure\", ascending=False)\n",
                ")\n",
                "\n",
                "print(\"\\nAverage Disruption Indicators by Route:\")\n",
                "route_summary.head(20)"
            ]
        },
        # Cell 15 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 14 — Live supply-route risk prediction\n",
                "\n",
                "def predict_supply_route_risk(\n",
                "    route_disruption,\n",
                "    shipping_delay,\n",
                "    freight_cost_change,\n",
                "    trade_volume_exposure,\n",
                "    india_import_exposure,\n",
                "    india_export_exposure,\n",
                "    energy_route_exposure,\n",
                "    commodity_exposure,\n",
                "    conflict_intensity\n",
                "):\n",
                "    row = pd.DataFrame([{\n",
                "        \"route_disruption\": route_disruption,\n",
                "        \"shipping_delay\": shipping_delay,\n",
                "        \"freight_cost_change\": freight_cost_change,\n",
                "        \"trade_volume_exposure\": trade_volume_exposure,\n",
                "        \"india_import_exposure\": india_import_exposure,\n",
                "        \"india_export_exposure\": india_export_exposure,\n",
                "        \"energy_route_exposure\": energy_route_exposure,\n",
                "        \"commodity_exposure\": commodity_exposure,\n",
                "        \"conflict_intensity\": conflict_intensity\n",
                "    }])\n",
                "\n",
                "    prediction = BEST_MODEL.predict(row)[0]\n",
                "\n",
                "    output = {\n",
                "        \"prediction\": prediction,\n",
                "        \"model\": BEST_MODEL_NAME\n",
                "    }\n",
                "\n",
                "    if hasattr(BEST_MODEL, \"predict_proba\"):\n",
                "        probabilities = BEST_MODEL.predict_proba(row)[0]\n",
                "        output[\"probabilities\"] = dict(\n",
                "            zip(BEST_MODEL.classes_, probabilities)\n",
                "        )\n",
                "\n",
                "    return output\n",
                "\n",
                "\n",
                "# Demonstration input\n",
                "result = predict_supply_route_risk(\n",
                "    route_disruption=70,\n",
                "    shipping_delay=65,\n",
                "    freight_cost_change=20,\n",
                "    trade_volume_exposure=60,\n",
                "    india_import_exposure=75,\n",
                "    india_export_exposure=45,\n",
                "    energy_route_exposure=70,\n",
                "    commodity_exposure=60,\n",
                "    conflict_intensity=75\n",
                ")\n",
                "\n",
                "print(\"Sample Live Prediction Result:\")\n",
                "print(result)"
            ]
        },
        # Cell 16 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 15 — Save the best trained model\n",
                "\n",
                "import joblib\n",
                "\n",
                "os.makedirs(\"models\", exist_ok=True)\n",
                "\n",
                "MODEL_PATH = (\n",
                "    \"models/\"\n",
                "    \"feature8_india_supply_route_risk_model.joblib\"\n",
                ")\n",
                "\n",
                "joblib.dump(\n",
                "    BEST_MODEL,\n",
                "    MODEL_PATH\n",
                ")\n",
                "\n",
                "print(\"Saved:\", MODEL_PATH)"
            ]
        },
        # Cell 17 - Code
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Cell 16 — Final workflow summary\n",
                "\n",
                "print(\n",
                "    '''\n",
                "FINAL WORKFLOW\n",
                "\n",
                "Real labelled route/event data\n",
                "        ↓\n",
                "Data validation + preprocessing\n",
                "        ↓\n",
                "Train/Test Split\n",
                "        ↓\n",
                "5 syllabus classifiers\n",
                "        ↓\n",
                "5-Fold Cross Validation\n",
                "        ↓\n",
                "Model comparison\n",
                "        ↓\n",
                "Hyperparameter tuning\n",
                "        ↓\n",
                "Accuracy / Precision / Recall / F1\n",
                "        ↓\n",
                "Confusion Matrix + ROC-AUC\n",
                "        ↓\n",
                "Overfitting / Underfitting check\n",
                "        ↓\n",
                "Best model selection\n",
                "        ↓\n",
                "Route-wise analysis\n",
                "        ↓\n",
                "Save trained model\n",
                "        ↓\n",
                "New route-disruption input\n",
                "        ↓\n",
                "Actual India supply-route risk prediction\n",
                "\n",
                "IMPORTANT:\n",
                "- Only syllabus classifiers are used.\n",
                "- Do not fabricate training rows.\n",
                "- Do not fabricate metrics or probabilities.\n",
                "- The live prediction must come from the saved trained model.\n",
                "- Risk labels must come from the real labelled dataset.\n",
                "'''\n",
                ")"
            ]
        }
    ]

    nb = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {"name": "ipython", "version": 3},
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.10.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    # Save to root and notebooks directory
    with open("Feature_8_India_Supply_Route_Disruption_Intelligence.ipynb", "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)

    os.makedirs("notebooks", exist_ok=True)
    with open("notebooks/Feature_8_India_Supply_Route_Disruption_Intelligence.ipynb", "w", encoding="utf-8") as f:
        json.dump(nb, f, indent=2)

    print("Successfully generated Feature 8 notebook with 17 cells!")

if __name__ == "__main__":
    create_notebook()
